version: '3.1'
services:
  pgdb:
    image: "postgres:latest"
    container_name: ""
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    ports:
      - "54320:5432"
 